add buy token
MTthoas/Dex pull request #82
Opened 2024-04-25 13:38 UTC by Guiiz94

still missing some tests

2024-04-26 09:29 UTC, MTthoas requested changes
You can end your test before to push, enable an other review then your next commit on this branch.

2024-04-26 09:29 UTC, MTthoas commented on next-app/src/app/tokens/page.tsx
> +  const [amountToBuy, setAmountToBuy] = React.useState('');
try to type for simple values : `React.useState<string>('')`

2024-04-26 09:29 UTC, MTthoas commented on next-app/src/app/tokens/page.tsx
>  import { Button } from "../../components/ui/button";
@/components For Next.

In tsconfig an path as be configured :     
"paths": {
      "@/*": ["./src/*"]
    }

2024-04-26 09:29 UTC, MTthoas commented on next-app/src/app/tokens/page.tsx
> +import { abi } from "../../abi/Token.json";
Same as below, @/abi/Token.json

2024-05-21 10:23 UTC, MTthoas commented
Resolve conflict @Guiiz94

2024-05-26 12:02 UTC, MTthoas requested changes
Do not push broadcast folder

2024-05-26 12:06 UTC, MTthoas reviewed
Evite les git add .

2024-05-26 12:06 UTC, MTthoas commented on next-app/src/app/tokens/page.tsx
> +  const [amountToBuy, setAmountToBuy] = React.useState('');
Still not corrected

2024-05-26 12:06 UTC, MTthoas commented on next-app/src/app/tokens/page.tsx
> +import { abi } from "../../abi/Token.json";
Still not corrected

2024-05-26 12:06 UTC, MTthoas commented on next-app/src/app/tokens/page.tsx
>  import { Button } from "../../components/ui/button";
Still not corrected

2024-05-26 12:06 UTC, MTthoas commented on package-lock.json
Why there is these file ?

2024-05-26 12:06 UTC, MTthoas commented on package.json
Why there is these file ?

2024-05-26 12:12 UTC, MTthoas commented
+ 
![image](https://github.com/MTthoas/Dex/assets/92540288/9e3571fa-f088-481d-a4fb-9f4c9fece4c6)

2024-05-29 10:12 UTC, MTthoas commented on .DS_Store
>Does it usefull to push it ?

2024-05-29 10:12 UTC, MTthoas commented on contracts/.DS_Store
Same as below, does it usefull to push it ?

2024-05-29 10:24 UTC, MTthoas commented on contracts/src/Token.sol
Explication in french : 

Les fonctions que t'as créer associé à l'ERC20 n'ont pas besoin d'être créer. Elle existe déjà dans la lib Openzeppelin : https://docs.openzeppelin.com/contracts/4.x/erc20

En gros t'as juste besoin d'import comme cela : 

![image](https://github.com/MTthoas/Dex/assets/92540288/b99b60ae-bcac-4f28-91e7-6c6dc276e065)

Mais c'est pas tout, nous pour nos besoins on veut créer un ERC20 Upgreadable avec des fonctions spécifiques à notre app.

Et pour cela on peut créer un mock d'un ERC20 pour ajouter des fonctions à l'ERC20. Comme par exemple dans le code actuelle des nouvelles liquidityPools : 

![image](https://github.com/MTthoas/Dex/assets/92540288/69f36054-d6d1-4312-8288-dfbf1a3a4418)

Biensûr ce code est très minimaliste et peut être modifier pour ajouter différents besoins. Mais voilà le principe. Si des fonctions ne sont pas disponibles dans le contrat hérité, on en créer dans le mock.

Et pour les tests je te conseille comme on a fait en cours de simuler des cas d'examples via des Scripts. Moi par exemple le fichier test je l'oublie. Si on prend l'exemple du mock, voici notre ERC20 avec AccessManager et ERC20Upgreable : 
![image](https://github.com/MTthoas/Dex/assets/92540288/6c4faae3-e6ff-4297-80f0-5ffb8364d44b)

Et le setting up : 
![image](https://github.com/MTthoas/Dex/assets/92540288/413c2d9c-d97b-4938-8c51-9c2d86258ac5)

2024-05-29 10:30 UTC, MTthoas requested changes

2024-05-29 10:30 UTC, MTthoas commented on contracts/test/Staking.t.sol
> +contract ERC20Mock is IERC20 {
Là par exemple t'as fais le mock. Mais met le dans un fichier dedié car il sera utiliser par notre plusieurs contrats.

2024-05-29 10:30 UTC, MTthoas commented on contracts/src/Staking.sol
> +contract Staking is ReentrancyGuard {
Use ReentrancyGuardUpgradeable Instead.

2024-05-29 10:30 UTC, MTthoas commented on contracts/test/Staking.t.sol
> +// SPDX-License-Identifier: MIT
Tu ne créer pas de factory pour les stacking pools?

2024-05-29 10:30 UTC, MTthoas commented on next-app/src/app/staking/StakeCard.tsx
> +        <Card className="bg-[#1E1E2D] text-white rounded-lg shadow-lg">
Nice, par contre pour le bg, il est préférable que tu set un thème visible et compréhensive, genre un bg-gray tu vois. 
Shadcn implémente cette fonctionnalité, tu peux choisir il me semble : https://ui.shadcn.com/docs/theming

2024-05-29 12:24 UTC, Guiiz94 commented on next-app/src/app/staking/StakeCard.tsx
> +        <Card className="bg-[#1E1E2D] text-white rounded-lg shadow-lg">
Je viens de le modifier par une couleur qui ressemble, j'ai également modifier src/app/swap/SwapCard.tsx qui avait le même soucis (j'avais copié cette card pour avoir 2 cards similaires)

2024-05-29 12:24 UTC, Guiiz94 commented on contracts/test/Staking.t.sol
> +// SPDX-License-Identifier: MIT
à voir plus tard ça

2024-05-29 13:44 UTC, MTthoas requested changes

2024-05-29 13:44 UTC, MTthoas commented on contracts/src/Token.sol
T'as pas pris en compte ce commentaire pour Token : https://github.com/MTthoas/Dex/pull/82#discussion_r1618642019

2024-05-29 13:44 UTC, MTthoas commented on contracts/test/mock/MockIERC20.sol
T'as pas pris en compte ce commentaire pour Token : https://github.com/MTthoas/Dex/pull/82#discussion_r1618642019

2024-05-31 08:10 UTC, MTthoas approved these changes

2024-05-31 08:10 UTC, merged