feat: Front profil details
MTthoas/Dex pull request #98
Opened 2024-04-29 22:28 UTC by MTthoas

![image](https://github.com/MTthoas/Dex/assets/92540288/5721a66f-3e08-429b-bc80-2d4d42ce46db)

2024-04-30 19:42 UTC, Ronfflex commented on next-app/src/components/header/Header.tsx
> +  console.log(address);
Console log à retirer

2024-04-30 19:45 UTC, Ronfflex requested changes
console.log to remove

2024-05-21 10:53 UTC, Guiiz94 commented on next-app/src/app/profil/page.tsx
> +  console.log(user);
console.log to remove here too

2024-05-21 10:54 UTC, MTthoas commented on next-app/src/components/header/Header.tsx
> +  console.log(address);
```suggestion
```

2024-05-21 10:54 UTC, MTthoas commented on next-app/src/app/profil/page.tsx
> +  console.log(user);
```suggestion
```

2024-05-21 10:56 UTC, Guiiz94 commented on next-app/src/components/header/Header.tsx
> +  console.log(address);
```suggestion
```

2024-05-23 12:45 UTC, merged